name: "expose-tunnel"
description: "Simple action that can start local tunnel to your local machine and expose ports to the internet."
author: "Rei-x"
inputs:
  ports:
    description: "Ports to expose, example 3000,3001,3002"
    required: true
    default: "3000"
runs:
  using: "node16"
  main: "dist/index.js"
  post: "cleanup/index.js"
