name: "pull-request-preview"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  ports:
    description: "Ports to expose, example 3000,3001,3002"
    required: true
    default: "3000"
runs:
  using: "node16"
  main: "dist/index.js"
